services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/SimmeredBalls/laravel_project.git
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: php artisan migrate --force && php artisan serve --host=dpg-d0mi136mcj7s739b1lj0-a --port=5432
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pserv
          name: hotel
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: bread_db_dlbl
      - key: DB_USERNAME
        value: bread_man
      - key: DB_PASSWORD
        value: LDcRqNpStaK1ptBOi5vcyZTFRnWs3FyS
